### ISSUE TITLE
How to get keypoints in intermediate files?

### ISSUE THREAD

**Issue by yokinglou** [XuyangBai/PPF-FoldNet#10]
Thanks for your implementation of PPF-FoldNet.

I am curious about how to generate the keypoints in intermediate files. Are these keypoints generated by your algorithms or provided by 3DMatch?

Best,
Yoking

**Comment by XuyangBai** [comment]
Hi, I am not sure whether you are asking the keypoint for training or not. But as you can see here, I choose randomly selected point as keypoint for training
https://github.com/XuyangBai/PPF-FoldNet/blob/63af940632ad2350141e332314aab99f41766378/input_preparation.py#L52-L56
For testing, 3DMatch do provide keypoints which are also randomly generated.

**Comment by yokinglou** [comment]
Thanks for your reply. I ask keypoints that used for geometric registration task, since you provide a link to download the intermediate files which include the keypoints for registration.  Are these keypoints provided by 3DMatch and generated randomly (like you said for testing)?

**Comment by XuyangBai** [comment]
They are provided by 3DMatch and I think also generated randomly ...

See https://vision.princeton.edu/projects/2016/3DMatch/#geometric-registration-benchmark

![image](https://user-images.githubusercontent.com/15166089/138220938-40da6b50-0a26-407c-a9bd-2377f3dd7b78.png)

**Comment by yokinglou** [comment]
Get it. Thanks.
