### ISSUE TITLE
一个小问题 关于rgbd_fragments/scene_list_train.txt

### ISSUE THREAD

**Issue by kaede316** [XuyangBai/PPF-FoldNet#11]
文件夹里没有这个./data/3DMatch/rgbd_fragments/scene_list_train.txt"    文件
Traceback (most recent call last):
  File "input_preparation.py", line 172, in <module>
    with open("./data/3DMatch/rgbd_fragments/scene_list_train.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/3DMatch/rgbd_fragments/scene_list_train.txt'

**Comment by XuyangBai** [comment]
You can find it here http://vision.princeton.edu/projects/2016/3DMatch/downloads/rgbd-datasets/split.txt from http://3dmatch.cs.princeton.edu/#rgbd-reconstruction-datasets

**Comment by kaede316** [comment]
oh&nbsp; THX, I forget a download link in preparation. I will try again.&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "XuyangBai/PPF-FoldNet"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Dec 10, 2021 07:08 PM
***@***.***&gt;;
Cc:&nbsp;"Liu ***@***.***&gt;;"State ***@***.***&gt;;
Subject:&nbsp;Re: [XuyangBai/PPF-FoldNet] 一个小问题 关于rgbd_fragments/scene_list_train.txt (Issue #11)





 
You can find it here http://vision.princeton.edu/projects/2016/3DMatch/downloads/rgbd-datasets/split.txt from http://3dmatch.cs.princeton.edu/#rgbd-reconstruction-datasets
