### ISSUE TITLE
Unsupported image format in Prepare the data

### ISSUE THREAD

**Issue by roxanasoto** [XuyangBai/PPF-FoldNet#2]
Hello
When I prepared the train data using script/fuse_fragments_3DMatch.py to fuse rgbd fragments obtained an error in console:
```
Start making fragments
2 scenes
  Start scene rgbd-scenes-v2-scene_05
  1 sequences
    Start seq-01
[ScalableTSDFVolume::Integrate] Unsupported image format.
[ScalableTSDFVolume::Integrate] Unsupported image format.
[ScalableTSDFVolume::Integrate] Unsupported image format.
[ScalableTSDFVolume::Integrate] Unsupported image format.
...
[ScalableTSDFVolume::Integrate] Unsupported image format.
Write PLY failed: point cloud has 0 points.
    Finished seq-01
  Finished scene rgbd-scenes-v2-scene_06
Finished making fragments
```
And I don't find the .ply files with the points clouds

**Comment by XuyangBai** [comment]
Hi, sorry for the confusion. Some of the scenes(name begin with 'analysis') in 3DMatch RGBD datasets have no color images. So the release code here is for the scene without color images, so if you use it for the scenes with color images, the image format is uncorrect. I have updated  the code for both with depth and without depth situation. Try the newest version.

**Comment by roxanasoto** [comment]
ok, Thanks so much, I don't have any problem concerning the fusion, but when I executed the code **"input_preparation.py"** obtained in my console:
`Finish rgbd-scenes-v2-scene_05, time: 8.916854858398438e-05
`
I see that It didn't read point cloud and voxel downsample, neither choose reference point(or interest point) from the point cloud. Neither the steps that you specified in the **README.md** . I think that is because I need any file with the name .color into the file "./data/3DMatch/{scene}/seq-01".?

 Also, the variable **downsample** isn't defined and it's generated an error when executed only "input_preparation.py" or "train.py"

`An exception of type <class 'NameError'> occurred for rgbd-scenes-v2-scene_05/seq-01/cloud_bin_0, Argument: 
 ("name 'downsample' is not defined",)`

**Comment by XuyangBai** [comment]
Sorry. The main function of `input_preparation.py` is buggy, I mixed it with my previous data pipeline. I shouldn't check the `filename.__contains__('color')` because, after the fusion we only have a `.ply` and a `.pose.npy` for each point cloud fragment.  

And also I should add one default value to the variable `downsample`. I will update the code later. Thank you :)
