### ISSUE TITLE
how to get gt.log

### ISSUE THREAD

**Issue by zwyking** [XuyangBai/PPF-FoldNet#5]
hello 
Rencently i try to read evaluate_ppfnet.py, however i can't find how to generate the corresponding gt.log. Does this file need to download or run other .py files to get?

**Comment by XuyangBai** [comment]
Hi, you can download it from [here.](http://3dmatch.cs.princeton.edu/#geometric-registration-benchmark)

**Comment by zwyking** [comment]
> Hi, you can download it from here.

ok，thank you~

**Comment by kaede316** [comment]
> hello Rencently i try to read evaluate_ppfnet.py, however i can't find how to generate the corresponding gt.log. Does this file need to download or run other .py files to get?
Hello, did u  run the preparation.py and evaluate.py successfully?
