### ISSUE TITLE
Training leads to crash randomly

### ISSUE THREAD

**Issue by WilliamKRobert** [XuyangBai/PPF-FoldNet#8]
When I run your code, my computer crashed and rebooted at line trainer.py/self.evaluate(0). I suspected it might relate to the conflict of some packages. Could you provide a complete list of your package versions? Such as PyTorch, tensorboardX, ect.? And your cuda and nvidia driver versions?

**Comment by XuyangBai** [comment]
Hi @WilliamKRobert 

The package versions are shown in `environment.yml` and I use `CUDA 9.0`

**Comment by WilliamKRobert** [comment]
I created an environment exactly copying yours and used the same cuda version but the issue still exits. I am pretty sure it is raised when exec ```output=self.model(patches)``` in trainer.py/self.evaluate(0). 

Anyone experienced the same issue?
